#!/bin/bash

# # debug
# set -o xtrace

if [[ ! -t 0 ]]; then
    declare FILES=$(cat /dev/stdin | tr '\n' ' ')
fi

declare SRCDIR=$(dirname $(readlink -e $0))

declare QUERY="$1"
declare RG_PREFIX="rg --column --line-number --no-heading --with-filename --color=always --smart-case"
declare FZF_DEFAULT_COMMAND="${FZF_CMD:=$RG_PREFIX $QUERY ${FILES[@]}}"

declare VIEWER HEADER LESS_SCROLL="less +{2}g"
if [[ -f $(which bat 2> /dev/null) ]]; then
    HEADER='~4,'
    VIEWER="bat --style=full --color=always --paging=always -H {2} --pager '$LESS_SCROLL'"
else
    VIEWER="$LESS_SCROLL -N '+/{q}'"
fi
declare FZF_DEFAULT_OPTS="--exact --multi"

declare PARSE_LINES="cat {+f} | cut -d: -f1 | uniq"

fzf --ansi --prompt='? ' --query "$QUERY" --disabled --delimiter : \
    --header-first \
    --header "« F1 help, C-s recursive search, C-f filter files, RET view, M-RET open »" \
    --bind "f1:execute(man -l $SRCDIR/help.1 || true)" \
    --preview "$VIEWER {1}" \
    --preview-window "border-left:${HEADER},+{2}-3" \
    --bind "enter:execute($VIEWER {1})" \
    --bind "alt-enter:execute($EDITOR +{2} {1})" \
    --bind "change:reload($RG_PREFIX {q} ${FILES[@]} || true)" \
    --bind "ctrl-s:select-all+execute($PARSE_LINES | fzf-search || true)+deselect-all" \
    --bind "ctrl-f:select-all+execute($PARSE_LINES | fzf-file {q} || true)+deselect-all"
