#!/bin/bash

# # debug
# set -o xtrace

# QUERY is optionally set externally: QUERY='foo bar' fzf-file
declare QUERY
if [[ ! -t 0 ]]; then		# stdin not attached to a tty
    unset FZF_DEFAULT_COMMAND
else
    FZF_DEFAULT_COMMAND="rg --files $@" # support multiple directories
fi

declare SRCDIR=$(dirname $(readlink -e $0))

declare VIEWER HEADER
if [[ -f $(which bat 2> /dev/null) ]]; then
    HEADER='~4'
    if [[ -n $QUERY ]]; then
	VIEWER="bat --style=full --color=always --paging=always --pager 'less \"+/$QUERY\"'"
    else
	VIEWER="bat --style=full --color=always --paging=always"
    fi
else
    if [[ -n $QUERY ]]; then
	VIEWER="less -NS '+/$QUERY'"
    else
	VIEWER="less -NS"
    fi
fi
declare FZF_DEFAULT_OPTS="--ansi --header-first --exact --multi"

fzf --prompt='> ' \
    --header "« F1 help, C-s recursive search, RET view, M-RET open »" \
    --bind "f1:execute(man -l $SRCDIR/help.1 || true)" \
    --preview "$VIEWER {1}" \
    --preview-window "border-left:$HEADER" \
    --bind "enter:execute($VIEWER {1})" \
    --bind "alt-enter:execute($EDITOR {1})" \
    --bind "ctrl-s:select-all+execute(uniq {+f} | fzf-search ${QUERY} || true)+deselect-all"
