#!/bin/bash

# # debug
# set -o xtrace

# if [[ ! -t 0 ]]; then
#     declare FILES=$(cat /dev/stdin | tr '\n' ' ')
# fi
# declare FZF_DEFAULT_COMMAND="${FZF_CMD:=rg --files ${FILES[@]}}"

declare SRCDIR=$(dirname $(readlink -e $0))

declare QUERY="$1"
unset FZF_DEFAULT_COMMAND

if [[ -f $(which bat 2> /dev/null) ]]; then
    declare VIEWER="bat --style=full --color=always --paging=always --pager 'less \"+/$QUERY\"'"
else
    declare VIEWER="less -N '+/$QUERY'"
fi
declare FZF_DEFAULT_OPTS="--exact --multi"

fzf --ansi --prompt='> ' \
    --header-first \
    --header "« F1 help, C-s recursive search, RET view, M-RET open »" \
    --bind "f1:execute(man -l $SRCDIR/help.1 || true)" \
    --preview "$VIEWER {1}" \
    --preview-window 'border-left:~4' \
    --bind "enter:execute($VIEWER {1})" \
    --bind "alt-enter:execute($EDITOR {1})" \
    --bind "ctrl-s:select-all+execute(uniq {+f} | fzf-search ${QUERY} || true)+deselect-all"
