#!/bin/bash

# # debug
# set -o xtrace

# if [[ ! -t 0 ]]; then
#     declare FILES=$(cat /dev/stdin | tr '\n' ' ')
# fi
# declare FZF_DEFAULT_COMMAND="${FZF_CMD:=rg --files ${FILES[@]}}"

declare QUERY="$1"
unset FZF_DEFAULT_COMMAND

declare VIEWER="bat --style=full --color=always --pager 'less \"+/$QUERY\"'"
declare FZF_DEFAULT_OPTS="--exact --multi"

fzf --ansi --prompt='> ' \
    --preview "$VIEWER {1}" \
    --preview-window 'border-left:~4' \
    --bind "enter:execute($VIEWER {1})" \
    --bind "alt-enter:execute($EDITOR {1})" \
    --bind "ctrl-s:select-all+execute(uniq {+f} | fzf-search ${QUERY} || true)+deselect-all"
